line-length = 150
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[format]
# exclude = ["*.ipynb"]

# Like Black:
# use double quotes for strings.
quote-style = "double"

# indent with spaces, rather than tabs.
indent-style = "space"

# respect magic trailing commas.
skip-magic-trailing-comma = false

# automatically detect the appropriate line ending.
line-ending = "auto"


[lint]
# exclude = ["*.ipynb"]

select = [
    "F",  # Pyflakes
    "E",  # a subset of the pycodestyle
    "I"  # isort
]

fixable = ["ALL"]
ignore = [
    "TD",  # TODO
    "D1",  # Missing docstring
]
