name: "[C]ontinuous [I]ntegration"
on:
  push:

env:
  OS: ubuntu-latest

  PYTHON_VERSION: 3.12.x

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: percebus/github-actions-python/.github/actions/setup@main

      - name: install.ba.sh
        run: bash scripts/install.ba.sh

      - uses: percebus/github-actions-node/.github/actions/setup@main

      - name: pypyr lint
        run: uv run pypyr -- lint stats=True

      - name: pypyr test
        run: uv run pypyr -- ci lint=False

      - uses: percebus/github-actions-testing/.github/actions/junit@main
        with:
          tests_name: "" # disables actions/test-reporter. It doesn't like pytest's junit format
          files_pattern: test-results.xml
